version: "3.8"

services:
  olire-data:
    build: ./data
    volumes:
      - ./data/schema.sql:/docker-entrypoint.initdb.d/schema.sql
      - olire-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: olire
      MYSQL_ROOT_PASSWORD: password # CHANGE_ME 😡!!!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart:  unless-stopped
    environment:
      PMA_HOST: olire-data
      MYSQL_ROOT_PASSWORD: password

  scrape:
    build: ./scrape
    volumes:
      - ./scrape:/app
    depends_on:
      - olire-data

  olire-webapp:
    build: ./olire-webapp
    ports:
      - "3000:3000"
    volumes:
      - ./olire-webapp:/app

volumes:
  olire-data: # persistent storage for database
